import { Annual } from './annual';

export const ANNUALS: Annual[] = [
  { id: 1, name: 'Single Tomato 6" or 1 Gal. Pot', price: '4.50', inStock: true },
  { id: 2, name: 'All Vegetable Plants Single Box - 4 pieces', price: '2.75', inStock: true },
  { id: 3, name: 'All Vegetable Plants Full Flat - 12 boxes', price: '22.00', inStock: true },
  { id: 4, name: 'Herbs 9 cm - 4" - 4.5" Pot', price: '3.95', inStock: true },
  { id: 5, name: 'Basil Single Box', price: '2.75', inStock: true },
  { id: 6, name: 'Parsley Single Box', price: '2.75', inStock: true },
  { id: 7, name: 'Celery Single Box - 4 pieces', price: '2.75', inStock: true },
  { id: 8, name: 'Rosemary 4" - 5" Pot', price: '3.95', inStock: true },
  { id: 9, name: 'Rosemary 1 Gallon', price: '8.99', inStock: true },
  { id: 10, name: 'Rosemary 2 Gallon', price: '15.00', inStock: true },
  { id: 11, name: 'Strawberry Plants 4" Pot', price: '2.95', inStock: true },
  { id: 12, name: 'Urn (Plastic) 12"-14"', price: '24.00', inStock: true },
  { id: 13, name: 'Urn (Plastic) 15"-16"', price: '49.99', inStock: true },
  { id: 14, name: 'Wall Planter 25"', price: '35.00', inStock: true },
  { id: 15, name: 'Potted Flowers 10"', price: '15.00', inStock: true },
  { id: 16, name: 'Potted Flowers 12"', price: '20.00', inStock: true },
  { id: 17, name: 'Potted Flowers 14"', price: '29.00', inStock: true },
  { id: 18, name: 'Mixed Flowers 12"', price: '25.00', inStock: true },
  { id: 19, name: 'Square Planter with Mix Flowers 12x12', price: '25.00', inStock: true },
  { id: 20, name: 'Square Planter with Mix Flowers 14x14', price: '29.00', inStock: true },
  { id: 21, name: 'Bowls with Flowers 12"', price: '15.00', inStock: true },
  { id: 22, name: 'Bowls with Flowers 14"', price: '17.00', inStock: true },
  { id: 23, name: 'Bowls with Flowers 16"', price: '19.00', inStock: true },
  { id: 24, name: 'Dahlia 6" Pot', price: '5.95', inStock: true },
  { id: 25, name: 'Gerbera Daisy 5" Pot', price: '4.95', inStock: true },
  { id: 26, name: 'Lantana 5" Pot', price: '4.95', inStock: true },
  { id: 27, name: 'Pegasus 5" Pot', price: '3.95', inStock: true },
  { id: 28, name: 'Ysotoma 5" Pot', price: '3.95', inStock: true },
  { id: 29, name: 'Angelface 5" Pot', price: '3.95', inStock: true },
  { id: 30, name: 'Pentas 5" Pot', price: '3.95', inStock: true },
  { id: 31, name: 'Cuphea 5" Pot', price: '3.95', inStock: true },
  { id: 32, name: 'Non-Stop Begonia 5" Pot', price: '3.95', inStock: true },
  { id: 33, name: 'Potato Vine (Ipomoea) 4" Pot', price: '3.95', inStock: true },
  { id: 34, name: 'Dragon Wing Begonia 5" Pot', price: '3.95', inStock: true },
  { id: 35, name: 'Summerwings Begonia 5" Pot', price: '3.95', inStock: true },
  { id: 36, name: 'New Guinea Sun Impatiens 5" Pot', price: '3.95', inStock: true },
  { id: 37, name: 'Bright Lights Yellow Daisy 5" Pot', price: '2.95', inStock: true },
  { id: 38, name: 'Geranium or Ivy Geranium 4.5" Pot', price: '2.95', inStock: true },
  { id: 39, name: 'Bedding Plants', price: '2.75', inStock: true },
  { id: 40, name: 'Full Flat (12 boxes)', price: '22.00', inStock: true },
  { id: 41, name: 'Hanging Baskets 6"', price: '8.99', inStock: true },
  { id: 42, name: '10" Boston Fern', price: '19.00', inStock: true },
  { id: 43, name: '10" All varieties (3 strings)', price: '16.00', inStock: true },
  { id: 44, name: '16" Light Wood Basket', price: '28.00', inStock: true },
  { id: 45, name: '12" Hanging Basket Mix (4 strings)', price: '25.00', inStock: true },
  { id: 46, name: 'Hanging Bag', price: '25.00', inStock: true },
  { id: 47, name: '16" Square Tall Planter', price: '95.00', inStock: true },
  { id: 48, name: 'Spikes 4.5" Pot', price: '2.95', inStock: true },
  { id: 49, name: 'Red Spike 5" Pot', price: '7.99', inStock: true },
  { id: 50, name: 'Citronella 5" Pot', price: '4.95', inStock: true },
  { id: 51, name: 'Citronella 2 Gallon or 10" Pot', price: '16.00', inStock: true },
];
