import { LandscapeItem } from './LandscapeItems';

export const LandscapeItems: LandscapeItem[] = [
  { id: 1, name: 'Garden Bench – Bluestone', price: 219.0, inStock: true },
  { id: 2, name: 'Curved Bluestone Garden Bench', price: 239.0, inStock: true },
  { id: 3, name: 'Small Hexagon', price: 309.0, inStock: true },
  { id: 4, name: 'Maplewood Stepping Stone', price: 12.99, inStock: true },
  { id: 5, name: '5-Way Deck Block or Regular Deck Block', price: 12.99, inStock: true },
  { id: 6, name: 'Campfire Stone', price: 12.99, inStock: true },
  { id: 7, name: 'BBQ Block', price: 8.25, inStock: true },
  { id: 8, name: 'Ready Step', price: 125.0, inStock: true },
  { id: 9, name: 'Garden Charms', price: 12.99, inStock: true },
  { id: 10, name: 'Round Stepping Stone Natural', price: 18.95, inStock: true },
  { id: 11, name: 'Hexagon Paver', price: 2.99, inStock: true },
  { id: 12, name: 'Border Lock – All Colours', price: 2.66, inStock: true },
  { id: 13, name: 'Rustic Edge – All Colours', price: 3.47, inStock: true },
  { id: 14, name: 'Wedge Rock Cornerstone', price: 6.59, inStock: true },
  { id: 15, name: 'Wedge Rock Pewter', price: 6.59, inStock: true },
  { id: 16, name: 'Wedge Stone – All Colours', price: 4.99, inStock: true },
  { id: 17, name: 'Wall Stone – All Colours', price: 4.99, inStock: true },
  { id: 18, name: 'Fortress Wall', price: 5.15, inStock: true },
  { id: 19, name: 'Tudor Edge', price: 2.83, inStock: true },
  { id: 20, name: 'Kendal Stone', price: 9.35, inStock: true },
  { id: 21, name: 'Handy Wall', price: 3.35, inStock: true },
  { id: 22, name: 'Ravello Wall (Multi-Length)', price: 14.95, inStock: true },
  { id: 23, name: 'Ravello Wall (Pillar Unit)', price: 4.65, inStock: true },
  { id: 24, name: 'Como Cap', price: 31.95, inStock: true },
  { id: 25, name: 'Chelsey Pillar Cap', price: 79.99, inStock: true },
  { id: 26, name: 'Covington Stone – Small', price: 2.19, inStock: true },
  { id: 27, name: 'Covington Stone – Large', price: 3.69, inStock: true },
  { id: 28, name: 'Covington Stone – Mega', price: 6.47, inStock: true },
  { id: 29, name: 'Brick Pattern – All Colours', price: 6.19, inStock: true },
  { id: 30, name: 'Euro Pattern – All Colours', price: 6.19, inStock: true },
  { id: 31, name: 'Cobble Pattern – All Colours', price: 6.19, inStock: true },
  { id: 32, name: 'Plank Slab – Oak Grey', price: 9.99, inStock: true },
  { id: 33, name: 'Field Stone – All Colours', price: 9.99, inStock: true },
  { id: 34, name: 'Terra Square – Oak Moss', price: 9.99, inStock: true },
  { id: 35, name: 'Slab – Red Natural', price: 2.5, inStock: true },
  { id: 36, name: 'Square Paver – All Colours', price: 5.25, inStock: true },
  { id: 37, name: 'Diamond Pattern', price: 8.25, inStock: true },
  { id: 38, name: 'Diamond Pattern – Natural', price: 8.25, inStock: true },
  { id: 39, name: 'Brick Pattern – Pewter', price: 8.25, inStock: true },
  { id: 40, name: 'Stretcher – Natural', price: 5.25, inStock: true },
  { id: 41, name: 'Quarry Slab – Bluestone Santa-Fe', price: 12.99, inStock: true },
  { id: 42, name: 'Carrera Medium', price: 11.99, inStock: true },
  { id: 43, name: 'BM-1 or BM-6 (Custom Blend)', price: 38.0, inStock: true },
  { id: 44, name: 'Pro-Mix HP with Mycorrhizae', price: 40.0, inStock: true },
  { id: 45, name: 'Agro-Mix – Lambert', price: 18.0, inStock: true },
  { id: 46, name: 'Perlite', price: 34.0, inStock: true },
  { id: 47, name: 'Peat Moss', price: 30.0, inStock: true },
  { id: 48, name: 'Snap Edge Paver Restraint', price: 20.0, inStock: true },
  { id: 49, name: '10\" Steel Spike', price: 0.99, inStock: true },
  { id: 50, name: "20' Strip", price: 25.0, inStock: true },
  { id: 51, name: "60' Roll", price: 79.0, inStock: true },
  { id: 52, name: "100' Roll", price: 129.0, inStock: true },
  { id: 53, name: "7.5' Brick/Paver Edging", price: 20.0, inStock: true },
  { id: 54, name: 'Steel Stake', price: 1.25, inStock: true },
  { id: 55, name: 'Plastic Connector', price: 1.75, inStock: true },
  { id: 56, name: 'Angled Connector (60°, 90°, 120°)', price: 8.99, inStock: true },
  { id: 57, name: 'Peat Moss (2.2 cu ft)', price: 14.0, inStock: true },
  { id: 58, name: 'Kryptonite Soil', price: 46.0, inStock: true },
  { id: 59, name: 'Play Sand', price: 5.5, inStock: true },
  { id: 60, name: 'Limestone Screening', price: 5.5, inStock: true },
  { id: 61, name: 'Horticultural Lime', price: 25.0, inStock: true },
  { id: 62, name: 'Top Soil Enriched with Compost', price: 4.95, inStock: true },
  { id: 63, name: 'Premium Lawn Soil', price: 6.95, inStock: true },
  { id: 64, name: 'Herb – Vegetable Potting Soil', price: 6.95, inStock: true },
  { id: 65, name: 'Premium Potting Soil Mix', price: 7.99, inStock: true },
  { id: 66, name: 'Premium Patio Soil Mix with Plant Food', price: 8.25, inStock: true },
  { id: 67, name: '3 Way Mix', price: 5.95, inStock: true },
  { id: 68, name: 'Compost Plus', price: 5.99, inStock: true },
  { id: 69, name: 'Composted Manure', price: 4.59, inStock: true },
  { id: 70, name: '3/4\\" Stone Clear', price: 5.95, inStock: true },
  { id: 71, name: 'Pea Gravel', price: 5.95, inStock: true },
  { id: 72, name: 'White Marble (Small or Large)', price: 8.25, inStock: true },
  { id: 73, name: 'Beach Stone', price: 7.99, inStock: true },
  { id: 74, name: 'Crushed Red Tile', price: 7.99, inStock: true },
  { id: 75, name: 'Rose Granite', price: 8.59, inStock: true },
  { id: 76, name: 'Black Granite', price: 8.59, inStock: true },
  { id: 77, name: 'Pink Quartz', price: 15.0, inStock: true },
  { id: 78, name: 'Red Lava Rock', price: 14.99, inStock: true },
  { id: 79, name: 'Royal Gorge', price: 16.0, inStock: true },
  { id: 80, name: 'Black Lava Rock', price: 16.0, inStock: true },
  { id: 81, name: 'Cedar Bark Mulch', price: 5.99, inStock: true },
  { id: 82, name: 'Mocha Brown Mulch', price: 5.99, inStock: true },
  { id: 83, name: 'Red Devil Mulch', price: 5.99, inStock: true },
  { id: 84, name: 'Black Beauty Mulch', price: 5.99, inStock: true },
  { id: 85, name: 'Rustic Red Mulch', price: 6.99, inStock: true },
  { id: 86, name: 'Canada Red Mulch', price: 5.99, inStock: true },
  { id: 87, name: 'Hemlock Grow Better Mulch', price: 8.99, inStock: true },
  { id: 88, name: 'Pine Nuggets (Large)', price: 10.99, inStock: true },
];
