import { Product } from './product';

export const PRODUCTS: Product[] = [
  { id: 1, name: 'Adam’s Needle Yucca', price: '28.00', inStock: true },
  { id: 2, name: 'Azalea Girards Fuchsia', price: '59.00', inStock: true },
  { id: 3, name: 'Azalea Girards Hot Shot', price: '59.00', inStock: true },
  { id: 4, name: 'Azalea Girards Rose', price: '59.00', inStock: true },
  { id: 5, name: 'Azalea Herbert', price: '59.00', inStock: true },
  { id: 6, name: 'Black Cedar 36-42', price: '56.00', inStock: true },
  { id: 7, name: 'Black-Eyed Susan', price: '14.00', inStock: true },
  { id: 8, name: 'Blue Moon Wisteria', price: '35.00', inStock: true },
  { id: 9, name: 'Blue Princess Holly', price: '45.00', inStock: true },
  { id: 10, name: 'Blue Rug Juniper 1 gal', price: '15.00', inStock: true },
  { id: 11, name: 'Blue Star Juniper 3 gal', price: '25.00', inStock: true },
  { id: 12, name: 'Boulevard Cypress 1 gal', price: '15.00', inStock: true },
  { id: 13, name: 'Boxwood Green Mountain 1 gal', price: '15.00', inStock: true },
  { id: 14, name: 'Boxwood Green Mountain 2 gal', price: '25.00', inStock: true },
  { id: 15, name: 'Boxwood Multi Pompom', price: '249.00', inStock: true },
  { id: 16, name: 'Bridalwreath Spirea 2 gal', price: '25.00', inStock: true },
  { id: 17, name: 'Bristol Ruby Weigela 2 gal', price: '25.00', inStock: true },
  { id: 18, name: 'Bristol Ruby Weigela Std', price: '79.00', inStock: true },
  { id: 19, name: 'Buddleia Black Knight (Butterfly Bush)', price: '25.00', inStock: true },
  { id: 20, name: 'Buddleia Ile de France (Butterfly Bush)', price: '25.00', inStock: true },
  { id: 21, name: 'Buddleia Nanho Blue (Butterfly Bush)', price: '25.00', inStock: true },
  { id: 22, name: 'Buddleia Pink Delight (Butterfly Bush)', price: '25.00', inStock: true },
  { id: 23, name: 'Calgary Carpet Juniper 2 gal', price: '28.00', inStock: true },
  { id: 24, name: 'Castle Rouge Holly', price: '45.00', inStock: true },
  { id: 25, name: 'Climbing Hydrangea', price: '30.00', inStock: true },
  { id: 26, name: 'Compact Euonymus', price: '29.00', inStock: true },
  { id: 27, name: 'Concord Barberry 3 gal', price: '35.00', inStock: true },
  { id: 28, name: 'Coral Bells (Autumn Glow)', price: '16.00', inStock: true },
  { id: 29, name: 'Coral Bells (Black Olive)', price: '16.00', inStock: true },
  { id: 30, name: 'Coral Bells (Melting Fire)', price: '16.00', inStock: true },
  { id: 31, name: 'Creeping Baby’s Breath', price: '14.00', inStock: true },
  { id: 32, name: 'Crimson Sentry Maple', price: '99.00', inStock: true },
  { id: 33, name: "Degroot's Cedar 5 gal 24-30", price: '50.00', inStock: true },
  { id: 34, name: 'Dense Yew 5 gal 12-15', price: '48.00', inStock: true },
  { id: 35, name: 'Diablo Ninebark 2 gal', price: '25.00', inStock: true },
  { id: 36, name: 'Dwarf Alberta Spruce', price: '40.00', inStock: true },
  { id: 37, name: 'Dwarf Burning Bush 2 gal', price: '29.00', inStock: true },
  { id: 38, name: 'Dwarf Burning Bush Std', price: '119.00', inStock: true },
  { id: 39, name: 'Dwarf Emerald Cedar', price: '69.00', inStock: true },
  { id: 40, name: 'Dwarf Hinoki Cypress', price: '69.00', inStock: true },
  { id: 41, name: 'Dwarf Korean Lilac 2 gal', price: '30.00', inStock: true },
  { id: 42, name: 'Dwarf Serbian Spruce', price: '180.00', inStock: true },
  { id: 43, name: 'Emerald Cedar', price: '28.00', inStock: true },
  { id: 44, name: 'Emerald Cedar 30-36', price: '50.00', inStock: true },
  { id: 45, name: 'Emerald Cedar 42-48', price: '69.00', inStock: true },
  { id: 46, name: 'Emerald Cedar 54-60', price: '89.00', inStock: true },
  { id: 47, name: 'Emerald Cedar Multi Pompom', price: '149.00', inStock: true },
  { id: 48, name: 'Emerald Cedar Spiral', price: '159.00', inStock: true },
  { id: 49, name: 'Emerald Gaiety Euonymus 1 gal', price: '13.00', inStock: true },
  { id: 50, name: 'Emerald Gaiety Euonymus 2 gal', price: '20.00', inStock: true },
  { id: 51, name: 'Emerald n Gold Euonymus 1 gal', price: '13.00', inStock: true },
  { id: 52, name: 'Emerald n Gold Euonymus 2 gal', price: '28.00', inStock: true },
  { id: 53, name: 'Flame Amur Maple', price: '219.00', inStock: true },
  { id: 54, name: 'Forest Pansy Redbud', price: '275.00', inStock: true },
  { id: 55, name: 'Forsythia 2 gal', price: '25.00', inStock: true },
  { id: 56, name: 'Globe Cedar Little Giant 7 gal', price: '25.00', inStock: true },
  { id: 57, name: 'Globe White Spruce', price: '150.00', inStock: true },
  { id: 58, name: 'Golden Falls Redbud', price: '260.00', inStock: true },
  { id: 59, name: 'Golden Globe Cedar 5 gal 12-1', price: '30.00', inStock: true },
  { id: 60, name: 'Golden Threadleaf Cypress 1 gal', price: '15.00', inStock: true },
  { id: 61, name: 'Golden Threadleaf Cypress 3 gal', price: '30.00', inStock: true },
  { id: 62, name: 'Golden Vicary Privet 2 gal', price: '25.00', inStock: true },
  { id: 63, name: 'Rose of Sharon Aphrodite', price: '28.00', inStock: true },
  { id: 64, name: 'Rose of Sharon Blue Bird', price: '28.00', inStock: true },
  { id: 65, name: 'Rose of Sharon Blue Chiffon Std', price: '125.00', inStock: true },
  { id: 66, name: 'Rose of Sharon Collie Mullens', price: '28.00', inStock: true },
  { id: 67, name: 'Rose of Sharon Pink Chiffon Std', price: '125.00', inStock: true },
  { id: 68, name: 'Hicks Yew 5/7 gal 15-18', price: '50.00', inStock: true },
  { id: 69, name: 'Hills Yew 1 gal', price: '16.00', inStock: true },
  { id: 70, name: 'Hills Yew 5/7 gal 15-18', price: '50.00', inStock: true },
  { id: 71, name: 'Himalayan Birch', price: '209.00', inStock: true },
  { id: 72, name: 'Holmstrump Cedar 5/7 gal 42-4', price: '60.00', inStock: true },
  { id: 73, name: 'Hydrangea Annabelle', price: '29.00', inStock: true },
  { id: 74, name: 'Hydrangea Bobo', price: '35.00', inStock: true },
  { id: 75, name: 'Hydrangea Bobo Std', price: '125.00', inStock: true },
  { id: 76, name: 'Hydrangea Cherry-Go-Round', price: '39.00', inStock: true },
  { id: 77, name: 'Hydrangea Grandiflora Std', price: '115.00', inStock: true },
  { id: 78, name: 'Hydrangea Kimono', price: '39.00', inStock: true },
  { id: 79, name: "Hydrangea Let's Dance Arriba", price: '39.00', inStock: true },
  { id: 80, name: 'Hydrangea Limelight', price: '35.00', inStock: true },
  { id: 81, name: 'Hydrangea Limelight Std', price: '135.00', inStock: true },
  { id: 82, name: 'Hydrangea Little Lime Punch Std', price: '135.00', inStock: true },
  { id: 83, name: 'Hydrangea Little Lime Std', price: '135.00', inStock: true },
  { id: 84, name: 'Hydrangea Pinky Winky', price: '35.00', inStock: true },
  { id: 85, name: 'Hydrangea Pinky Winky Std', price: '135.00', inStock: true },
  { id: 86, name: 'Hydrangea Puffer Fish', price: '35.00', inStock: true },
  { id: 87, name: 'Hydrangea Sky View', price: '39.00', inStock: true },
  { id: 88, name: 'Hydrangea Tiny Quick Fire Std', price: '135.00', inStock: true },
  { id: 89, name: 'Hydrangea Vanilla Strawberry', price: '39.00', inStock: true },
  { id: 90, name: 'Hydrangea Vanilla Strawberry Std', price: '135.00', inStock: true },
  { id: 91, name: 'Hydrangea Venice', price: '35.00', inStock: true },
  { id: 92, name: 'Hydrangea Vienna', price: '35.00', inStock: true },
  { id: 93, name: 'Hydrangea Wee Bit Giddy', price: '35.00', inStock: true },
  { id: 94, name: 'Ice Plant', price: '14.00', inStock: true },
  { id: 95, name: 'Icee Blue Juniper 1 gal', price: '15.00', inStock: true },
  { id: 96, name: 'Jantar Cedar 5 gal 24-30', price: '60.00', inStock: true },
  { id: 97, name: 'Japanese Maple (Crimson Queen)', price: '119.00', inStock: true },
  { id: 98, name: 'Japanese Maple (Emperor 1)', price: '159.00', inStock: true },
  { id: 99, name: 'Japanese Maple (Red Dragon)', price: '99.00', inStock: true },
  { id: 100, name: 'Weeping Larch Std', price: '125.00', inStock: true },
  { id: 101, name: 'Limeglow Juniper 1 gal', price: '15.00', inStock: true },
  { id: 102, name: 'Limeglow Juniper 2 gal', price: '25.00', inStock: true },
  { id: 103, name: 'Little Gem Spruce', price: '59.00', inStock: true },
  { id: 104, name: 'Little Gem Spruce Std', price: '135.00', inStock: true },
  { id: 105, name: 'Saucer Magnolia', price: '195.00', inStock: true },
  { id: 106, name: 'Midnight Express Redbud', price: '150.00', inStock: true },
  { id: 107, name: 'Moffat Blue Juniper', price: '59.00', inStock: true },
  { id: 108, name: 'Mountain Fire', price: '35.00', inStock: true },
  { id: 109, name: 'Mugho Pine 3 gal', price: '45.00', inStock: true },
  { id: 110, name: 'Old Gold Juniper 3 gal', price: '30.00', inStock: true },
  { id: 111, name: 'Old Gold Pompom', price: '199.00', inStock: true },
  { id: 112, name: 'Pincushion Flower (Butterfly Blue)', price: '14.00', inStock: true },
  { id: 113, name: 'Pincushion Flower (Pink Mist)', price: '14.00', inStock: true },
  { id: 114, name: 'Purpleleaf Sand Cherry', price: '28.00', inStock: true },
  { id: 115, name: 'Pyramid Boxwood 24-30 7 gal', price: '60.00', inStock: true },
  { id: 116, name: 'Red Oak', price: '149.99', inStock: true },
  { id: 118, name: 'Rheingold Cedar 1 gal', price: '15.00', inStock: true },
  { id: 119, name: 'Rheingold Cedar 3 gal', price: '35.00', inStock: true },
  { id: 120, name: 'Rose Glow Barberry 3 gal', price: '35.00', inStock: true },
  { id: 121, name: 'Royal Red Maple FP', price: '209.00', inStock: true },
  { id: 122, name: 'Dappled Willow Std', price: '129.00', inStock: true },
  { id: 123, name: 'Savannah Sunset Ninebark', price: '39.00', inStock: true },
  { id: 124, name: 'Serviceberry', price: '139.00', inStock: true },
  { id: 125, name: 'Siberian Carpet Cypress', price: '39.00', inStock: true },
  { id: 126, name: 'Snowcap Shasta Daisy', price: '14.00', inStock: true },
  { id: 127, name: 'Spiraea Double Play Gold', price: '30.00', inStock: true },
  { id: 128, name: 'Spiraea Double Play Red', price: '30.00', inStock: true },
  { id: 129, name: 'Spiral Dwarf Alberta Spruce', price: '209.00', inStock: true },
  { id: 130, name: 'Sunburst Locust', price: '150.00', inStock: true },
  { id: 131, name: 'Reblooming Lilac Dark Purple', price: '39.00', inStock: true },
  { id: 132, name: 'Reblooming Lilac Dark Purple Std', price: '135.00', inStock: true },
  { id: 133, name: 'Dwarf Korean Lilac Std', price: '115.00', inStock: true },
  { id: 134, name: 'Tricolor Beech', price: '289.00', inStock: true },
  { id: 135, name: '3 in 1 Blueberry', price: '50.00', inStock: true },
  { id: 136, name: "Vanderwolf's Pyramid Pine", price: '280.00', inStock: true },
  { id: 137, name: 'Walker Weeping Caragana', price: '139.00', inStock: true },
  { id: 138, name: 'Weigela Bubbly Wine', price: '39.00', inStock: true },
  { id: 139, name: 'Weigela My Monet Purple', price: '35.00', inStock: true },
  { id: 140, name: 'Weigela Sonic Bloom Red', price: '35.00', inStock: true },
  { id: 141, name: 'Weigela Vinho Verde', price: '35.00', inStock: true },
  { id: 142, name: 'Whipcord Cedar', price: '59.00', inStock: true },
  { id: 143, name: 'White Cedar 7 gal 30-36', price: '49.00', inStock: true },
  { id: 144, name: 'Emerald Cedar 60-66', price: '98.00', inStock: true },
  { id: 145, name: 'Emerald Cedar 6ft', price: '198.00', inStock: true },
];
