import { Product } from './product';

export const PRODUCTLIST: Product[] = [
  {
    id: 1,
    name: 'Black Cedar',
    price: 56.0,
    inStock: true,
    size: '36"-42"',
  },
  {
    id: 2,
    name: "Degroot's Cedar",
    price: 50.0,
    inStock: true,
    size: '5 gal. 24"-30"',
  },
  {
    id: 3,
    name: 'Emerald Cedar',
    price: 50.0,
    inStock: true,
    size: '30"-36"',
  },
  {
    id: 4,
    name: 'Emerald Cedar',
    price: 69.0,
    inStock: true,
    size: '42"-48"',
  },
  {
    id: 5,
    name: 'Emerald Cedar',
    price: 89.0,
    inStock: true,
    size: '54"-60"',
  },
  {
    id: 6,
    name: 'Jantar Cedar',
    price: 60.0,
    inStock: true,
    size: '5 gal. 24"-30"',
  },
  {
    id: 7,
    name: 'White Cedar',
    price: 49.0,
    inStock: true,
    size: '7 gal. 30"-36"',
  },
  {
    id: 8,
    name: 'pyramid Boxwood',
    price: 60.0,
    inStock: true,
    size: '7 gal. 24"-30"',
  },
  {
    id: 9,
    name: 'Boulevard Cypress',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 10,
    name: 'Little Giant Globe Cedar',
    price: 25.0,
    inStock: true,
    size: '5/7 gal.',
  },
  {
    id: 11,
    name: 'Golden Globe Cedar',
    price: 30.0,
    inStock: true,
    size: '5 gal.',
  },
  {
    id: 12,
    name: 'Dense Yew',
    price: 48.0,
    inStock: true,
    size: '5 gal. 12"-15"',
  },
  {
    id: 13,
    name: 'Forsythia',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 14,
    name: 'Diablo Ninebark',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 15,
    name: 'Dwarf Korean Lilac',
    price: 30.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 16,
    name: 'Bridalwreath Spirea',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 17,
    name: 'Bristol Ruby Weigela',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 18,
    name: 'Wine & Rose Weigela',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 19,
    name: 'Rose Glow Barberry',
    price: 35.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 20,
    name: 'Concord Barberry',
    price: 35.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 21,
    name: 'Holmstrump Cedar',
    price: 60.0,
    inStock: true,
    size: '5/7 gal. 42"-48"',
  },
  {
    id: 22,
    name: 'Royal Red Maple F.P.',
    price: 209.0,
    inStock: true,
  },
  {
    id: 23,
    name: 'Red Oak',
    price: 149.99,
    inStock: true,
    size: '10 gal.',
  },
  {
    id: 24,
    name: 'Dappled Willow Standard',
    price: 129.0,
    inStock: true,
  },
  {
    id: 25,
    name: 'Dwarf Korean Lilac Standard',
    price: 115.0,
    inStock: true,
  },
  {
    id: 26,
    name: 'Reblooming Lilac Standard',
    price: 135.0,
    inStock: true,
  },
  {
    id: 27,
    name: '3 in 1 Blueberry Bush',
    price: 50.0,
    inStock: true,
  },
  {
    id: 28,
    name: 'Emperor 1 Japanese Maple',
    price: 159.0,
    inStock: true,
  },
  {
    id: 29,
    name: 'Russian Cypress',
    price: 39.0,
    inStock: true,
  },
  {
    id: 30,
    name: 'Dwarf Alberta Spruce',
    price: 40.0,
    inStock: true,
  },
  {
    id: 31,
    name: 'Dwarf Alberta Spruce Spiral',
    price: 209.0,
    inStock: true,
  },
  {
    id: 32,
    name: 'Emerald Petite',
    price: 69.0,
    inStock: true,
  },
  {
    id: 33,
    name: 'Smaragd Cedar',
    price: 28.0,
    inStock: true,
  },
  {
    id: 34,
    name: 'Whipcord Cedar',
    price: 59.0,
    inStock: true,
  },
  {
    id: 35,
    name: 'Holly',
    price: 45.0,
    inStock: true,
  },
  {
    id: 36,
    name: 'Yucca',
    price: 28.0,
    inStock: true,
  },
  {
    id: 37,
    name: 'Purple Leaf Sandcherry',
    price: 28.0,
    inStock: true,
  },
  {
    id: 38,
    name: 'Climbing Hydrangea',
    price: 30.0,
    inStock: true,
  },
  {
    id: 39,
    name: 'Crimson Queen Japanese Maple',
    price: 119.0,
    inStock: true,
  },
  {
    id: 40,
    name: 'Red Dragon Japanese Maple',
    price: 99.0,
    inStock: true,
  },
  {
    id: 41,
    name: 'Dwarf Hinoki Cypress',
    price: 69.0,
    inStock: true,
  },
  {
    id: 42,
    name: 'Little Gem Norway Spruce',
    price: 59.0,
    inStock: true,
  },
  {
    id: 43,
    name: 'Castle Rouge Holly',
    price: 45.0,
    inStock: true,
  },
  {
    id: 44,
    name: 'Annabelle Hydrangea',
    price: 29.0,
    inStock: true,
  },
  {
    id: 45,
    name: 'Cherry Go Round Hydrangea',
    price: 39.0,
    inStock: true,
  },
  {
    id: 46,
    name: 'Kimono Hydrangea',
    price: 39.0,
    inStock: true,
  },
  {
    id: 47,
    name: "Let's Dance Arriba Hydrangea",
    price: 39.0,
    inStock: true,
  },
  {
    id: 48,
    name: "Let's Dance Sky View Hydrangea",
    price: 39.0,
    inStock: true,
  },
  {
    id: 49,
    name: 'Wee Bit Giddy Hydrangea',
    price: 35.0,
    inStock: true,
  },
  {
    id: 50,
    name: 'Bobo Hydrangea',
    price: 35.0,
    inStock: true,
  },
  {
    id: 51,
    name: 'Limelight Hydrangea',
    price: 35.0,
    inStock: true,
  },
  {
    id: 52,
    name: 'Pinky Winky Hydrangea',
    price: 35.0,
    inStock: true,
  },
  {
    id: 53,
    name: 'Pufferfish Hydrangea',
    price: 39.0,
    inStock: true,
  },
  {
    id: 54,
    name: 'Vanilla Strawberry Hydrangea',
    price: 39.0,
    inStock: true,
  },
  {
    id: 55,
    name: 'Savannah Sunset Ninebark',
    price: 39.0,
    inStock: true,
  },
  {
    id: 56,
    name: 'Double Play Gold Spirea',
    price: 30.0,
    inStock: true,
  },
  {
    id: 57,
    name: 'Double Play Red Spirea',
    price: 30.0,
    inStock: true,
  },
  {
    id: 58,
    name: 'Reblooming Lilac',
    price: 35.0,
    inStock: true,
  },
  {
    id: 59,
    name: 'Bubbly Wine Weigela',
    price: 39.0,
    inStock: true,
  },
  {
    id: 60,
    name: 'My Monet Weigela',
    price: 39.0,
    inStock: true,
  },
  {
    id: 61,
    name: 'Vinho Verde Weigela',
    price: 35.0,
    inStock: true,
  },
  {
    id: 62,
    name: 'Blue Moon Wisteria',
    price: 35.0,
    inStock: true,
  },
  {
    id: 63,
    name: 'Red Mountain Flame Ice Plant',
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 64,
    name: "White Creeping Baby's Breath",
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 65,
    name: 'Autumn Glow Coral Bells',
    price: 16.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 66,
    name: 'Black Olive Coral Bells',
    price: 16.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 67,
    name: 'Melting Fire Coral Bells',
    price: 16.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 68,
    name: 'Snowcap Shasta Daisy',
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 69,
    name: 'Goldstrum Coneflower',
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 70,
    name: 'Butterfly Blue Pincushion',
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 71,
    name: 'Pink Mist Pincushion',
    price: 14.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 72,
    name: 'Black night Butterfly Bush',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 73,
    name: 'Ile De France Butterfly Bush',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 74,
    name: 'Nanho Blue Butterfly Bush',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 75,
    name: 'Pink Delight Butterfly Bush',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 76,
    name: 'Compact Burning Bush',
    price: 29.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 77,
    name: 'Aphrodite Rose of Sharon',
    price: 28.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 78,
    name: 'Blue Bird Rose of Sharon',
    price: 28.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 79,
    name: 'Venice Raven Hydrangea',
    price: 35.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 80,
    name: 'Vienna Rawl Hydrangea',
    price: 35.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 81,
    name: 'Mountain Fire',
    price: 35.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 82,
    name: 'Sonic Bloom Red Weigela',
    price: 35.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 83,
    name: "Hick's Yew",
    price: 50.0,
    inStock: true,
    size: '5/7 gal. 15"-18"',
  },
  {
    id: 84,
    name: "Hill's Yew",
    price: 50.0,
    inStock: true,
    size: '5/7 gal. 15"-18"',
  },
  {
    id: 85,
    name: 'Dwarf Burning Bush Standard',
    price: 119.0,
    inStock: true,
  },
  {
    id: 86,
    name: 'Emeral Cedar Spiral',
    price: 159.0,
    inStock: true,
    size: '42"-48"',
  },
  {
    id: 87,
    name: 'Boxwood Multi PomPom',
    price: 249.0,
    inStock: true,
    size: '30"-36"',
  },
  {
    id: 88,
    name: 'Old Gold Pompom',
    price: 109.0,
    inStock: true,
    size: '7 gal.',
  },
  {
    id: 89,
    name: 'Crimson Sentry Maple F.P.',
    price: 199.0,
    inStock: true,
  },
  {
    id: 90,
    name: 'Bristol Ruby Weigela',
    price: 79.0,
    inStock: true,
    size: '7 gal.',
  },
  {
    id: 91,
    name: 'Emerald Gaiety Euonymus',
    price: 13.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 92,
    name: "Emerald n' Gold Euonymus",
    price: 13.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 93,
    name: 'Green Mountain Boxwood',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 93,
    name: 'Blue Rug Juniper',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 94,
    name: 'Golden Threadleaf Cypress',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 95,
    name: 'Icee Blue Juniper',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 96,
    name: 'Limeglow Juniper',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 97,
    name: 'Rheingold Cedar',
    price: 15.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 98,
    name: "Hill's Yew",
    price: 16.0,
    inStock: true,
    size: '1 gal.',
  },
  {
    id: 99,
    name: 'Emerald Gaiety Euonymus',
    price: 20.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 100,
    name: "Emerald n' Gold Euonymus",
    price: 20.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 101,
    name: 'Green Mountain Boxwood',
    price: 28.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 102,
    name: 'Calgary Carpet Juniper',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 103,
    name: 'Limeglow Juniper',
    price: 28.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 104,
    name: 'Old Gold Juniper',
    price: 25.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 105,
    name: 'Golden Threadleaf Cypress',
    price: 30.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 106,
    name: 'Rheingold Cedar',
    price: 30.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 107,
    name: 'Mugho Pine',
    price: 35.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 108,
    name: 'Blue Star Juniper',
    price: 45.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 109,
    name: 'Golden Vicary Privet',
    price: 25.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 110,
    name: 'Dwarf Burning Bush',
    price: 29.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 111,
    name: 'Flame Amur Maple',
    price: 219.0,
    inStock: true,
    size: '15 gal.',
  },
  {
    id: 112,
    name: 'Serviceberry',
    price: 139.0,
    inStock: true,
    size: '5 gal.',
  },
  {
    id: 113,
    name: 'Sunburst Locust',
    price: 150.0,
    inStock: true,
    size: '15 gal.',
  },
  {
    id: 114,
    name: 'Red Oak',
    price: 149.99,
    inStock: true,
    size: '10 gal.',
  },
  {
    id: 115,
    name: 'Moffat Blue Juniper',
    price: 59.0,
    inStock: true,
    size: '3 gal.',
  },
  {
    id: 116,
    name: "Girard's Fuchsia Azalea",
    price: 59.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 117,
    name: "Girard's Hot Shot Azalea",
    price: 59.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 118,
    name: "Girard's Rose Azalea",
    price: 59.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 119,
    name: 'Herbert Azalea',
    price: 59.0,
    inStock: true,
    size: '2 gal.',
  },
  {
    id: 120,
    name: 'Tricolor Beach',
    price: 289.0,
    inStock: true,
  },
];
